# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default=' ', max_length=250),
            preserve_default=False,
        ),
    ]
