# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 08:24
from __future__ import unicode_literals
from datetime import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publication_date',
            field=models.DateTimeField(default=datetime.utcnow()),
            preserve_default=False,
        ),
    ]
