# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_article_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='optional_image',
            field=models.ImageField(default=None, upload_to=b''),
            preserve_default=False,
        ),
    ]
