# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 13:04
from __future__ import unicode_literals

import articles.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20161207_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='hero_image',
            field=models.ImageField(upload_to=articles.utils.get_upload_location),
        ),
        migrations.AlterField(
            model_name='article',
            name='optional_image',
            field=models.ImageField(blank=True, upload_to=articles.utils.get_upload_location),
        ),
    ]
